# Generated by Django 3.1.2 on 2020-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201023_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='averageRating',
            new_name='average_rating',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pageCount',
            new_name='page_count',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishedDate',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ratingsCount',
            new_name='ratings_count',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='books.Category'),
        ),
    ]
